apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-config-pvc3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc