apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-shard2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc