apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard1-headless-service
  labels:
    name: mongodb-shard1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb-shard1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-shard1
spec:
  selector:
    matchLabels:
      role: mongodb-shard1 # has to match .spec.template.metadata.labels
  serviceName: mongodb-shard1-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shard1
        tier: maindb
        replicaset: shard1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - shard1
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-shard1-container
          image: mongo:3.2
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "shard1"
            - "--dbpath"
            - "/mongo-disk"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-shard1-pvc
              mountPath: /mongo-disk
      volumes:
        - name: mongo-shard1-pvc
          persistentVolumeClaim:
            claimName: mongo-shard1-pvc